### ISSUE TITLE
Should artifacts go in src?

### ISSUE THREAD

**Issue by tcbegley** [imrehg/cdei-development#12]
Currently we have `data/` getting generated inside `src/`, but `artifacts/` in the root directory. Should we keep them in the same place. Or perhaps `data/` even belongs inside `artifacts/`?

**Comment by imrehg** [comment]
Both data (preprocessing) and artifacts can belong to the same folder. Wherever it goes, it should be a top level folder, though, so both `notebooks` and `src` can refer to it with relative paths. Does it make sense?

**Comment by tcbegley** [comment]
yep, makes perfect sense
