### ISSUE TITLE
Make plotly figure template?

### ISSUE THREAD

**Issue by tcbegley** [imrehg/cdei-development#24]
We can set some custom defaults with this: https://plotly.com/python/templates/

Would give figures a uniform look without much boilerplate.

**Comment by imrehg** [comment]
Looking at that to make it work on the JS side: https://plotly.com/javascript/layout-template/ 
Going to check how this might work in practice.

**Comment by tcbegley** [comment]
Oh great, yes JavaScript side could be nice too

**Comment by imrehg** [comment]
For the time being we just keep things simple, and set visuals in Python and take things over from there.
