### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by tcbegley** [imrehg/cdei-development#40]
This is a tracking issue for things to do to clean up the code.

- [x] favour `fig` over `fig.show()` in notebooks so that browser tabs aren't spawned when building locally
- [x] run `black` on all source, `black-nb` on all notebooks
- [x] check for unused imports
- [ ] sort imports
- [x] Use f-strings rather than old school string interpolation with `%`
- [ ] Consistent use of fairness terminology (e.g. demographic parity rather than independence)
- [x] Format floating point numbers to 3 decimal places

**Comment by imrehg** [comment]
I can add the `black`/`black-nb` check on the test side, basically not accepting notebooks where black would change stuff.

Looking at the other stuff as well.

And the `fig` vs `fig.show()` is good point, it's my lack of knowledge in the beginning.

**Comment by tcbegley** [comment]
> I can add the black/black-nb check on the test side

Sounds good. We had something like this in the old bitbucket pipelines that might be useful as a starting point?

> And the fig vs fig.show() is good point, it's my lack of knowledge in the beginning.

No worries, I didn't know about it either!

**Comment by imrehg** [comment]
Finished with what we wanted for now.
