### ISSUE TITLE
Collapsible element is highlighted when clicked

### ISSUE THREAD

**Issue by imrehg** [imrehg/cdei-development#76]
I think it doesn't look great, looking for options to do away with that highlight.

![Screenshot_2020-06-19_22-31-31](https://user-images.githubusercontent.com/38863/85180983-bf190c00-b27c-11ea-8e71-896fc9d9e959.png)

There's [`react-collapse`](https://github.com/nkbt/react-collapse) that we use at the moment.

An alternative is `react-component/collapse`, and there I see the highlight in in their demo already, though a bit less jarring: http://react-component.github.io/collapse/examples/custom-icon.html (also the demo already does the tabbing and expand-on-keypress, that we added manually, so it seems better equipped out of the box?)

Also looking at [`react-collapsible` ](https://github.com/glennflanagan/react-collapsible)which might be an alternative (and seems to need less code? but maybe that's just how they write their readme. Tried it out through the JSFiddle link in the repo). Less nice looking though.

Opening this issue to look at these for a quick facelift, if that's possible.

**Comment by tcbegley** [comment]
Think we can just add `outline: none` in CSS. This is happening because we made the element focusable to suppress the accessibility warnings.

But having said that, I'm totally open to using a different collapse element if there are more feature rich alternatives.

**Comment by imrehg** [comment]
I tried that, and it's not quite, as in that case tabbing through the page also doesn't highlight the element, but it should in that case. The example I have is that currently, the prev/next buttons behave as I expect it: no highlight on click but outline on tabbing through.

Will look into it a bit more as it is an interesting problem, but will make sure if I change anything, it doesn't interfere with the current #77 PR (as it shouldn't get in a way), we can always attempt to fix stuff when the reorg is done.

**Comment by imrehg** [comment]
Fixed by switching collapsibles in #88
