### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by tcbegley** [imrehg/cdei-development#94]
Currently we have only pinned a subset of the dependencies we're using. Might be worth installing contents of requirements.txt in a clean virtual environment and saving the output of `pip list` / `pip freeze` or something?

**Comment by imrehg** [comment]
@tcbegley do you mean freezing the dependencies of our dependencies? As the direct dependencies are frozen all already, as much as I can tell. If our dependencies' dependencies are included, then the  requirements can get quite confusing, IMHO. But maybe I'm missing something.

**Comment by tcbegley** [comment]
Yeah that’s what I meant. Maybe the dependencies of the dependencies get updated and break things in the distant future?

Agreed it’s confusing though
